### ISSUE TITLE
IP address not allowed error

### ISSUE THREAD

**Issue by gvko** [Jonahss/bitstamp-request#1]
The public endpoints are working fine for me, but the private ones return error `IP address not allowed`. I am sure that my API credentials are correct, because we use the Bitstamp API in a PHP solution as well.
Do you have any idea?

**Comment by Jonahss** [comment]
I have an idea, I saw this in their documentation:
`Do not make more than 600 requests per 10 minutes or we will ban your IP address`

^^ Maybe you went over that limit accidentally?

Your PHP code might be running from a different IP address?

**Comment by gvko** [comment]
I the problem was that the API key was attached to a certain IP of the production server. I got the admin of the office to provide me with an API key attached to the office IP. :)

**Comment by Jonahss** [comment]
Ah, good to know :)
